use_frameworks!

target '{{cookiecutter.project_name}}-iOS' do
  platform :ios, '10.0'
  podspec :path => '{{cookiecutter.project_name}}.podspec'
end

target '{{cookiecutter.project_name}}-macOS' do
  platform :osx, '10.10'
  podspec :path => '{{cookiecutter.project_name}}.podspec'
end

target '{{cookiecutter.project_name}}-tvOS' do
  platform :tvos, '10.0'
  podspec :path => '{{cookiecutter.project_name}}.podspec'
end

target '{{cookiecutter.project_name}}-watchOS' do
  platform :watchos, '3.0'
  podspec :path => '{{cookiecutter.project_name}}.podspec'
end
